### ISSUE TITLE
Change Electrical description

### ISSUE THREAD

**Issue by Sasha45** [JaydenB0/Team1515_Web#1]
Students in the electrics/pneumatics division have many responsibilities that directly
                            affect the robot's functions, performance, and the success of our team.
                            Electrical team members focus on robot wiring and piping. This
                            involves power distribution, voltage regulation, motor controlling, pneumatic contol, 
			    air compression, actuating pistons,  and creating a
                            powerful and competitive team robot!

**Comment by JaydenB0** [comment]
Changed the electrical description on  #commit eed661b
